language: python
sudo: false
python:
    - "2.7"
    # - "3.3"
    # - "3.4"
    # - "3.5"
    # - "pypy"
    # - "pypy3"
install:
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
