language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3.3-5.2-alpha1"
install:
    - pip install -U setuptools==33.1.1
    - pip install zc.buildout
    - buildout bootstrap
    - buildout tox:env=travis install test
script:
    - bin/test-travis -v1
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
